In [1]:
from src.project import Project

proj = Project('/Users/isabellechen/Dropbox @RU Dropbox/Isabelle Chen/example_data/20240115-1015-fly1-melWT_3do_sh_melWT_3do_gh','10_09_01MJPG-0000')

In [2]:
bg, calibration, feat, params, track = proj.read_project_data()

In [3]:
import pandas as pd
import numpy as np

def convert_data_to_df(data, col_names):
    n_flies, n_frames, n_flags = data.shape
    reshaped_data = data.reshape(-1, n_flags)

    df = pd.DataFrame(reshaped_data, columns=col_names)
    df['id'] = np.repeat(np.arange(n_flies), n_frames)

    return df

In [4]:
track_data = track['trk']['data']
feature_data = feat['feat']['data']

track_names = [i.replace(' ', '_') for i in track['trk']['names']]
feature_names = feat['feat']['names']

In [5]:
track_df = convert_data_to_df(track_data, track_names)
feature_df = convert_data_to_df(feature_data, feature_names)

In [6]:
# Concatenate along axis=1 (horizontally)
track_feature = pd.concat([feature_df, track_df], axis=1)

In [7]:
track_feature

,vel,ang_vel,min_wing_ang,max_wing_ang,mean_wing_length,axis_ratio,fg_body_ratio,contrast,dist_to_wall,dist_to_other,...,leg_5_y,leg_6_x,leg_6_y,leg_1_ang,leg_2_ang,leg_3_ang,leg_4_ang,leg_5_ang,leg_6_ang,id
0,27.760335,0.059031,0.070184,0.113363,1.904930,3.241620,3.105856,0.265803,2.909003,25.870275,...,NaN,NaN,NaN,-0.591355,1.570320,2.736041,NaN,NaN,NaN,0
1,27.760335,0.287484,0.060691,0.102101,1.902980,3.322472,3.112842,0.269980,2.683556,25.764119,...,128.0,NaN,NaN,-1.891430,-0.448297,0.890940,1.242397,2.760944,NaN,0
2,22.893499,0.987162,0.072418,0.099556,1.895876,3.391456,3.173063,0.268889,2.517328,25.661251,...,129.0,NaN,NaN,-2.927364,-1.520840,0.720157,1.561423,2.641311,NaN,0
3,15.135936,1.529196,0.080854,0.093614,1.895622,3.361646,3.224714,0.268279,2.412099,25.550027,...,128.0,NaN,NaN,-2.906173,-1.324485,0.654087,1.912728,2.493395,NaN,0
4,6.958983,1.393339,0.072333,0.095410,1.903336,3.249895,3.123369,0.276265,2.389758,25.459197,...,124.0,497.0,128.0,-2.955907,-1.266117,-0.723773,0.615680,1.790462,2.375198,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215995,16.330244,0.594309,0.020885,0.063930,2.200976,3.192546,2.480808,0.166200,5.350743,3.954129,...,946.0,NaN,NaN,-1.336897,-0.981502,0.688471,1.778683,2.762487,NaN,1
215996,16.729621,0.968933,0.020889,0.051766,2.192903,3.237779,2.493921,0.167686,5.325563,3.998637,...,NaN,NaN,NaN,-1.901137,0.804953,1.642987,2.757793,NaN,NaN,1
215997,18.949663,1.013950,0.020647,0.048799,2.201918,3.258233,2.505767,0.167309,5.305263,4.060245,...,NaN,NaN,NaN,-1.916883,1.062256,1.480833,2.702737,NaN,NaN,1
215998,19.587339,0.867803,0.022211,0.056043,2.214864,3.249690,2.528554,0.165846,5.254227,4.092901,...,940.0,351.0,955.0,-3.005526,-1.666470,-0.691837,0.849302,1.813714,2.641627,1
215999,16.861902,0.364111,0.031358,0.055220,2.207209,3.225881,2.540156,0.166744,5.176669,4.052698,...,957.0,NaN,NaN,-3.009404,-1.490226,0.725341,1.980493,2.540852,NaN,1

In [8]:
def load_data():
    return pd.read_hdf("/Users/isabellechen/Dropbox @RU Dropbox/Isabelle Chen/example_data/20240115-1015-fly1-melWT_3do_sh_melWT_3do_gh/dlc_output/20240115-1015-fly1-melWT_3do_sh_melWT_3do_ghDLC_dlcrnetms5_38mm-dyadFeb23shuffle1_50000_el.h5")

In [9]:
trk = load_data()

In [10]:
def select_data(full_data: pd.DataFrame, obj_id: str):
    return full_data.xs(obj_id, level="individuals", axis=1)

In [11]:
flypos = select_data(trk,"fly1")

In [12]:
flypos

scorer    DLC_dlcrnetms5_38mm-dyadFeb23shuffle1_50000                      \
bodyparts                                        head
coords                                              x        y likelihood
0                                             271.402  863.338        1.0
1                                             272.983  856.477        1.0
2                                             277.850  854.913        1.0
3                                             287.172  859.208        1.0
4                                             288.455  858.789        1.0
...                                               ...      ...        ...
107995                                        345.558  920.405        1.0
107996                                        355.155  921.314        1.0
107997                                        360.222  930.962        1.0
107998                                        365.912  934.860        1.0
107999                                        366.372  940.887        1.0

scorer                                                                 \
bodyparts   thorax                     abdomentip
coords           x        y likelihood          x        y likelihood
0          259.334  841.190        1.0    241.200  805.134        1.0
1          265.639  838.135        1.0    233.665  811.576        1.0
2          268.212  833.933        1.0    233.755  810.573        1.0
3          274.894  831.771        1.0    236.389  806.640        1.0
4          272.582  830.673        1.0    241.596  806.756        1.0
...            ...      ...        ...        ...      ...        ...
107995     335.405  892.021        1.0    302.460  863.150        1.0
107996     336.367  900.317        1.0    308.181  865.187        1.0
107997     342.913  910.994        1.0    313.031  874.242        1.0
107998     353.446  917.071        1.0    318.111  878.327        1.0
107999     351.748  922.496        1.0    324.607  887.802        1.0

scorer
bodyparts    wingL                        wingR
coords           x        y likelihood        x        y likelihood
0          230.391  782.541        1.0  229.568  784.601        1.0
1          229.521  783.312        1.0  227.845  784.933        1.0
2          228.726  783.009        1.0  226.710  784.587        1.0
3          232.146  783.984        1.0  225.869  788.180        1.0
4          228.878  786.511        1.0  227.704  790.686        1.0
...            ...      ...        ...      ...      ...        ...
107995     286.902  840.955        1.0  286.642  839.765        1.0
107996     297.001  845.686        1.0  259.868  755.706        1.0
107997     271.796  757.515        1.0  265.673  759.210        1.0
107998     215.093  800.539        1.0  306.739  862.326        1.0
107999         NaN      NaN        0.0  315.500  864.018        1.0

[108000 rows x 15 columns]

In [13]:
from src.project_dlc import *

In [14]:
flypos = remove_jumps(flypos, 6)

In [15]:
pcutoff=0.9
cop_ix = None
if cop_ix is not None:
    flypos.iloc[:int(cop_ix)]

In [16]:
likelihoods = flypos.xs('likelihood', level='coords', axis=1)

In [17]:
import warnings
warnings.filterwarnings("ignore", category=pd.errors.PerformanceWarning)

In [18]:
# indices = likelihoods[(likelihoods < 0.9).any(axis=1)].index.tolist()
# len(indices)
# flypos.loc[indices, :] = np.nan

cell_indices = [(row, col) for row, col in zip(*np.where(likelihoods < 0.9))]
for row, col in cell_indices:
    flypos.loc[row, likelihoods.columns[col]] = np.nan

In [19]:
flypos

scorer    DLC_dlcrnetms5_38mm-dyadFeb23shuffle1_50000                      \
bodyparts                                        head
coords                                              x        y likelihood
0                                             271.402  863.338        1.0
1                                             272.983  856.477        1.0
2                                             277.850  854.913        1.0
3                                             287.172  859.208        1.0
4                                             288.455  858.789        1.0
...                                               ...      ...        ...
107995                                        345.558  920.405        1.0
107996                                        355.155  921.314        1.0
107997                                        360.222  930.962        1.0
107998                                        365.912  934.860        1.0
107999                                        366.372  940.887        1.0

scorer                                                                 \
bodyparts   thorax                     abdomentip
coords           x        y likelihood          x        y likelihood
0          259.334  841.190        1.0    241.200  805.134        1.0
1          265.639  838.135        1.0    233.665  811.576        1.0
2          268.212  833.933        1.0    233.755  810.573        1.0
3          274.894  831.771        1.0    236.389  806.640        1.0
4          272.582  830.673        1.0    241.596  806.756        1.0
...            ...      ...        ...        ...      ...        ...
107995     335.405  892.021        1.0    302.460  863.150        1.0
107996     336.367  900.317        1.0    308.181  865.187        1.0
107997     342.913  910.994        1.0    313.031  874.242        1.0
107998     353.446  917.071        1.0    318.111  878.327        1.0
107999     351.748  922.496        1.0    324.607  887.802        1.0

scorer
bodyparts    wingL                        wingR
coords           x        y likelihood        x        y likelihood
0          230.391  782.541        1.0  229.568  784.601        1.0
1          229.521  783.312        1.0  227.845  784.933        1.0
2          228.726  783.009        1.0  226.710  784.587        1.0
3          232.146  783.984        1.0  225.869  788.180        1.0
4          228.878  786.511        1.0  227.704  790.686        1.0
...            ...      ...        ...      ...      ...        ...
107995     286.902  840.955        1.0  286.642  839.765        1.0
107996     297.001  845.686        1.0  259.868  755.706        1.0
107997     271.796  757.515        1.0  265.673  759.210        1.0
107998     215.093  800.539        1.0  306.739  862.326        1.0
107999         NaN      NaN        NaN  315.500  864.018        1.0

[108000 rows x 15 columns]

In [21]:
flydf = get_fly_params(flypos)

/Users/isabellechen/flytracker_analysis/src/calculate_dlc.py:39: RuntimeWarning: Mean of empty slice
  x_center, y_center = np.nanmean(x_coords, axis=1), np.nanmean(y_coords, axis=1)

In [22]:
from src.video import VideoInfo
video = VideoInfo("/Users/isabellechen/Dropbox @RU Dropbox/Isabelle Chen/example_data/20240115-1015-fly1-melWT_3do_sh_melWT_3do_gh/10_09_01MJPG-0000.avi")

In [23]:
flydf["time"] = video.get_timestamp()

In [24]:
flydf

,ori,centroid_x,centroid_y,lin_speed,left_wing_angle,right_wing_angle,inter_wing_dist,body_length,time
0,1.092144,246.37900,815.36080,0.000000,-0.020222,0.005581,2.218317,65.573367,0.000000
1,0.851593,245.93060,814.88660,7.831581,-0.136659,-0.101541,2.331655,59.682535,0.016667
2,0.788169,247.05060,813.40300,22.306670,-0.123074,-0.083358,2.560145,62.533228,0.033334
3,0.802668,251.29400,813.95660,51.352312,-0.038331,0.075875,7.550308,73.091092,0.050000
4,0.837670,251.84300,814.68300,10.926314,0.047060,0.109841,4.336923,70.022846,0.066667
...,...,...,...,...,...,...,...,...,...
107995,0.925545,311.39340,871.25920,74.581068,0.114412,0.105583,1.218072,71.662910,1799.933333
107996,0.873943,311.31440,857.64200,163.409150,-0.072448,-0.210277,97.340948,73.190141,1799.950000
107997,0.876846,310.72700,846.58460,132.875894,-0.260037,-0.223223,6.353279,73.784476,1799.966666
107998,0.868896,311.86020,878.62460,384.720401,0.168901,0.004434,110.528832,74.033207,1799.983333
107999,0.904183,339.55675,903.80075,449.149181,NaN,-0.111721,NaN,67.545040,1800.000000